name: Runs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Install TeXLive
      # Actually pick a version, do not point on master, or the build won't be reproducible
      uses: DanySK/setup-texlive-action@master
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib
    
    - name: make
      run: make
      
    - name: make run
      run: make run
      
    - name: make plot
      run: make plot
      
    - name: make clean
      run: make clean
